### ISSUE TITLE
Red5 saved file duration is not same

### ISSUE THREAD

**Issue by yanalavishnu** [Red5/red5-server#151]
I am using red5 1.0.6

This is my code to save a stream.

`@Override public void streamPublishStart(IBroadcastStream stream) {
    stream.saveAs("audio/"+username+"_"+System.currentTimeMillis(), true);
    insertInDB(System.currentTimeMillis()+"", "start", "audio", username, users.get(username).room, stream.getSaveFilename());
    super.streamPublishStart(stream);
}`

Sometimes the duration of the file is different from the stopTime - startTime. A stream was published for 12 minutes, but the file was around 45 minutes. In the file first 9 minutes was good then 9th minute to 42nd minute the file was empty(no audio) then from 42nd minute contains the audio from 9th minute of the stream.

Most of the times stream duration is not equal to saved file duration. Why does this occur?

**Comment by kojot1234** [comment]
Any idea when this may get resolved?

**Comment by mondain** [comment]
Red5 version 1.0.6 won't be getting updates, its very stale. If this is still an issue in version 1.0.9 let us know.

**Comment by kojot1234** [comment]
Still an issue in 1.0.9. Although I got around it with starting and closing NetConnection whenever the record button was pressed, instead of connecting when application loaded. It reconnect multiple times but seems to correct the issue.

I believe the problem is with duration being started when the connection is made and not when the stream starts publishing.

I've ended up going with nginx-rtmp-module for production release. Thanks for your work.
