### ISSUE TITLE
Red5 error #1069

### ISSUE THREAD

**Issue by gaelson** [Red5/red5-server#170]
# Issue

### Short description
__Brief description of what happened__
I get this error 
20:55:40:674 - Asynchronous code error - ReferenceError: Error #1069
20:55:40:674 - NetConnection.Connect.Success
20:55:48:726 - Asynchronous code error - ReferenceError: Error #1069

### Environment

[] Operating system and version: linux
[] Java version: 
[] Red5 version: 1.0

### Expected behavior
__Put as much detail here as possible__
I use Adobe Flash medai encoder to make a live streaming. I can connect correctly to the server.
when I try to view the video nothing appear. I use the demo publisher but nothing.
rtmp://localhost/oflaDemo
name: lives

### Actual behavior
__Put as much detail here as possible__

### Steps to reproduce
1. use Adobe flash media encoder
2. connect to the server
3. try to view live video with demo ofla publisher

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
Not certain which 1069 error you're getting, but this one shouldn't occur since we support startTransmit https://forums.adobe.com/thread/974491?start=0&tstart=0

https://github.com/Red5/red5-server/blob/d6ace47db13b91df279de47dbc1fa460d3708f23/src/main/java/org/red5/server/adapter/MultiThreadedApplicationAdapter.java#L1141
