### ISSUE TITLE
Question: upgrade-ability from 0.7.0?

### ISSUE THREAD

**Issue by dejl** [Red5/red5-server#197]
I have an old webapp written for red5 0.7.0 and I'm considering upgrading this.

Is there any document or information that could help me to achieve this goal? or, would this require major effort?

**Comment by dejl** [comment]
also, where can I obtain the source and releases for older versions such as 0.8.0?

**Comment by mondain** [comment]
There are some wiki pages that will help, there are quite a lot of changes since 0.7.0. You'll want to start by fixing the packages in your apps `scope` was added, see [chat example](https://github.com/Red5/red5-server/blob/master/src/main/server/webapps/chat/WEB-INF/red5-web.xml#L18)
Wiki pages: 
1. https://github.com/Red5/red5-server/wiki/Missing-Classes
1. https://github.com/Red5/red5-server/wiki/Runtime-Errors
1. https://github.com/Red5/red5-server/wiki/Release-Notes---1.0.7
