### ISSUE TITLE
red5-server will not start in latest ubuntu

### ISSUE THREAD

**Issue by hustler203** [Red5/red5-server#241]
# Issue

### Short description
__server will not start__

### Environment

[] Operating system and version: ubuntu-16.04.3-server-amd64
[] Java version: oracle  jdk-9.0.1
[] Red5 version: red5-server-1.0.10-M4

### Expected behavior
__server to start after clean install__

### Actual behavior
__  run   ./red5.sh &  and i get an bootstrap error code __

### Steps to reproduce
 following instructions on wiki

### Logs
__Starting Red5
Java HotSpot(TM) 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Red5 root: /usr/share/red5
Configuation root: /usr/share/red5/conf
Red5 server jar was found
URL list: [file:/usr/share/red5/red5-server.jar]
Bootstrap exception: null
java.lang.NullPointerException
        at org.red5.classloading.ClassLoaderBuilder.build(ClassLoaderBuilder.java:206)
        at org.red5.classloading.ClassLoaderBuilder.build(ClassLoaderBuilder.java:93)
        at org.red5.server.Bootstrap.bootStrap(Bootstrap.java:116)
        at org.red5.server.Bootstrap.main(Bootstrap.java:50)
Bootstrap exit
__

**Comment by mymalev** [comment]
Installation on Ubuntu 16.04.3 LTS

Job for red5-server.service failed because the control process exited with error code. See "systemctl status red5-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript red5-server, action "start" failed.
â— red5-server.service - LSB: Red5
   Loaded: loaded (/etc/init.d/red5-server; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Di 2017-12-12 16:11:40 CET; 15ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1230 ExecStart=/etc/init.d/red5-server start (code=exited, status=1/FAILURE)

Dez 12 16:11:35 h1288341.stratoserver.net red5-server[1230]:  * Starting Flash streaming server  red5-server
Dez 12 16:11:40 h1288341.stratoserver.net red5-server[1230]:    ...fail!
dpkg: Fehler beim Bearbeiten des Paketes red5-server (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurÃ¼ck
Trigger fÃ¼r libc-bin (2.23-0ubuntu9) werden verarbeitet ...
Trigger fÃ¼r systemd (229-4ubuntu21) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 red5-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@h1288341:~# service red5-server stop
root@h1288341:~# service red5-server start
Job for red5-server.service failed because the control process exited with error code. See "systemctl status red5-server.service" and "journalctl -xe" for details.

**Comment by mondain** [comment]
I suggest using JDK 8 until we've released with JDK 9 support. Your Ubuntu version doesnt matter, I use 16.x daily.

**Comment by hustler203** [comment]
thank you
