### ISSUE TITLE
Netstream.send metadata is not being dynamically updated

### ISSUE THREAD

**Issue by beetlejesss** [Red5/red5-server#37]
only initial set dataframe is stored in client broadcast stream, even when it has been updated

steps to reproduce:
1. from publisher - do: 
ns.send("@setDataFrame","onMetaData",{param:val});
2. notice the subscriber is only given the values from the first time

**Comment by Andy--S** [comment]
Easy fix. Remove the 'if null' check on ClientBroadcastStream. dispatching event.

**Comment by mondain** [comment]
Are you referring to the "metadata == null" on line 321? https://github.com/Red5/red5-server-common/blob/master/src/main/java/org/red5/server/stream/ClientBroadcastStream.java#L321

**Comment by Andy--S** [comment]
Yes sir!
The only worry being that recorded streams may be desirable to have both events embedded. So a large event recorded with dynamic metadata would have initial meta data and subsequent meta datas.  But that concern is secondary to live streams where it the latent subscribers shold receive the updated meta rather than the initial meta.  Think about a sports game where the score is updated in metadata through the duration. the live viewer would see the current scores, and we would want the recorded file to have the initial scores at the head.  
First fix would be the ability to updated it during streaming, and the second fix would be to  check into how it treats meta when serializing.

**Comment by mondain** [comment]
Removed @ https://github.com/Red5/red5-server-common/commit/27cb27be0d3806e5f370d453e546cd5a29633de7
